<a href="https://colab.research.google.com/github/amruta-katkar/AI-ML/blob/main/Backpropogation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)


In [ ]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])


In [ ]:
np.random.seed(1)
input_neurons = 2
hidden_neurons = 4
output_neurons = 1

In [ ]:
weights_input_hidden = np.random.uniform(size=(input_neurons, hidden_neurons))
weights_hidden_output = np.random.uniform(size=(hidden_neurons, output_neurons))
bias_hidden = np.random.uniform(size=(1, hidden_neurons))
bias_output = np.random.uniform(size=(1, output_neurons))

In [ ]:
weights_input_hidden

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01]])

In [ ]:
size=(input_neurons, hidden_neurons)

In [ ]:
size

(2, 4)

In [ ]:
weights_hidden_output

array([[0.39676747],
       [0.53881673],
       [0.41919451],
       [0.6852195 ]])

In [ ]:
learning_rate = 0.5

In [ ]:
epochs = 10000
for epoch in range(epochs):
    # Forward propagation
    hidden_input = np.dot(X, weights_input_hidden) + bias_hidden
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, weights_hidden_output) + bias_output
    final_output = sigmoid(final_input)

    # Compute error
    error = y - final_output

    # Backpropagation
    d_output = error * sigmoid_derivative(final_output)
    error_hidden = d_output.dot(weights_hidden_output.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Update weights and biases
    weights_hidden_output += hidden_output.T.dot(d_output) * learning_rate
    weights_input_hidden += X.T.dot(d_hidden) * learning_rate


In [ ]:
print("Final Output after Training:")
print(final_output.round())

Final Output after Training:
[[0.]
 [1.]
 [1.]
 [0.]]


In [ ]:
hidden_input

array([[ 0.20445225,  0.87811744,  0.02738759,  0.67046751],
       [ 2.71215287, -3.75871114,  6.19189161,  4.5469654 ],
       [ 3.49776428,  7.61097332, -3.83840213,  5.10083873],
       [ 6.0054649 ,  2.97414474,  2.32610189,  8.97733662]])

In [ ]:
hidden_output

array([[0.55093576, 0.70643196, 0.50684647, 0.66160783],
       [0.93773996, 0.02278262, 0.99795822, 0.98951185],
       [0.97062409, 0.99950526, 0.02107429, 0.99394525],
       [0.99754082, 0.95139231, 0.91101584, 0.99987378]])

In [ ]:
final_input


array([[-3.26773225],
       [ 3.85499091],
       [ 3.59250667],
       [-4.60150912]])

In [ ]:
final_output

array([[0.03669491],
       [0.97926524],
       [0.97320832],
       [0.00993694]])