# import all methods of numpy

In [1]:
from numpy import *


In [3]:
a = array([101,102,103,104,105])

In [4]:
a


array([101, 102, 103, 104, 105])

In [6]:
for i in a:
    print(i,end=" ")

101 102 103 104 105 

# linspace method

In [7]:
linspaceresult = linspace(90,105,3)

In [8]:
linspaceresult

array([ 90. ,  97.5, 105. ])

In [9]:
linspaceresult = linspace(90,80,3)

In [10]:
linspaceresult

array([90., 85., 80.])

# logspace method

In [12]:
logspaceresult=logspace(40,50,3,10)
logspaceresult

array([1.e+40, 1.e+45, 1.e+50])

In [16]:
b = array([1,2,3,4,5])
result = where(a>b,a,b)

result

array([101, 102, 103, 104, 105])

# nonzero method

In [17]:
r = nonzero(a)
r

(array([0, 1, 2, 3, 4], dtype=int64),)

# view method

In [21]:
array1 = array([100,200,300,400,23,235,6,3])
viewresult = array1.view()
array1[6] = 700
print(array1)
viewresult

[100 200 300 400  23 235 700   3]


array([100, 200, 300, 400,  23, 235, 700,   3])

# copy method

In [24]:
array1 = array([100,200,300,400,23,235,6,3])
copyresult = array1.copy()
array1[5] = 800
print(array1)
copyresult

[100 200 300 400  23 800   6   3]


array([100, 200, 300, 400,  23, 235,   6,   3])

# reshape method

In [33]:
a = array([1,2,3,4,5,6])

b = reshape(a,(2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

# flatten method

In [31]:
flattenresult = b.flatten()
flattenresult

array([1, 2, 3, 4, 5, 6])

# shape, size, ndim, itemsize

In [34]:
a.shape

(6,)

In [35]:
a.size

6

In [36]:
a.ndim

1

In [37]:
a.itemsize

4

In [40]:
type(a)

numpy.ndarray

In [68]:
# samplearray = zeros((2,4))
# print(samplearray)
# n=len(samplearray)
# print("Enter array element of 2 X 4 matrix",n)
# for i in range(n):
#     for j in range(len(samplearray[i])):
#         samplearray[i][j]=int(input("enter element"))
#     print

# for r in range(len(samplearray)):
#     for col in range(len(samplearray[r])):
#         print(samplearray[r][j],end=" ")
#     print()


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Enter array element of 2 X 4 matrix 2
enter element1
enter element2
enter element3
enter element4
enter element5
enter element6
enter element7
enter element8
4.0 4.0 4.0 4.0 
8.0 8.0 8.0 8.0 


### samplearray

In [43]:
print(samplearray)

8
